# Generated by Django 4.2 on 2023-04-28 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="category_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={"verbose_name_plural": "categories",},
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=100)),
                ("comments", models.CharField(max_length=100)),
                ("phone", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.CharField(blank=True, max_length=25000)),
                ("price", models.FloatField()),
                (
                    "instructions",
                    models.CharField(default="Available", max_length=25000),
                ),
                (
                    "image",
                    models.ImageField(default="default.png", upload_to="images/"),
                ),
                (
                    "labels",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Best Selling Foods", "Best Selling Foods"),
                            ("New Food", "New Food"),
                            ("Spicy Foods🔥", "Spicy Foods🔥"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "label_colour",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("danger", "danger"),
                            ("success", "success"),
                            ("primary", "primary"),
                            ("info", "info"),
                            ("warning", "warning"),
                        ],
                        max_length=15,
                    ),
                ),
                ("slug", models.SlugField(default="foods")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mainapp.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        choices=[(1, "Table 1"), (2, "Table 2"), (3, "Table 3")]
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(choices=[(2, "2"), (4, "4"), (6, "6")]),
                ),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rslug", models.SlugField()),
                ("review", models.TextField()),
                ("posted_on", models.DateField(default=django.utils.timezone.now)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Review", "verbose_name_plural": "Reviews",},
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("guests", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("11:00", "11:00 AM"),
                            ("11:30", "11:30 AM"),
                            ("12:00", "12:00 PM"),
                            ("12:30", "12:30 PM"),
                            ("13:00", "1:00 PM"),
                            ("13:30", "1:30 PM"),
                            ("18:00", "6:00 PM"),
                            ("18:30", "6:30 PM"),
                            ("19:00", "7:00 PM"),
                            ("19:30", "7:30 PM"),
                            ("20:00", "8:00 PM"),
                            ("20:30", "8:30 PM"),
                            ("21:00", "9:00 PM"),
                            ("21:30", "9:30 PM"),
                        ],
                        max_length=5,
                    ),
                ),
                ("special_requests", models.TextField(blank=True)),
                (
                    "reservation_type",
                    models.CharField(
                        choices=[
                            ("Lunch", "Lunch"),
                            ("Birthday", "Birthday"),
                            ("Anniversary", "Anniversary"),
                            ("Private Dinner", "Private Dinner"),
                            ("Wedding", "Wedding"),
                            ("Corporate", "Corporate"),
                            ("Rooftop Dinner", "Rooftop Dinner"),
                            ("Dinner", "Dinner"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.table"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordered", models.BooleanField(default=False)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "ordered_date",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Delivered", "Delivered")],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Cart Item", "verbose_name_plural": "Cart Items",},
        ),
    ]
