# Generated by Django 4.2 on 2023-04-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="capacity",
            field=models.IntegerField(
                choices=[
                    (2, "2"),
                    (2, "2"),
                    (2, "2"),
                    (4, "4"),
                    (4, "4"),
                    (2, "2"),
                    (4, "4"),
                    (4, "4"),
                    (4, "4"),
                    (6, "6"),
                    (6, "6"),
                    (4, "4"),
                    (10, "10"),
                    (4, "4"),
                    (4, "4"),
                    (10, "10"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.IntegerField(
                choices=[
                    (1, "Table 1"),
                    (2, "Table 2"),
                    (3, "Table 3"),
                    (4, "Table 4"),
                    (5, "Table 5"),
                    (6, "Table 6"),
                    (7, "Table 7"),
                    (8, "Table 8"),
                    (9, "Table 9"),
                    (10, "Table 10"),
                    (11, "Table 11"),
                    (12, "Table 12"),
                    (13, "Table 13"),
                    (14, "Table 14"),
                    (15, "Table 15"),
                    (16, "Table 16"),
                ]
            ),
        ),
    ]
